### ISSUE TITLE
wan down for a minute then up still no peers

### ISSUE THREAD

**Issue by wfleurant** [MassMesh/autoygg#7] opened 2020-08-11 17:06 UTC
we have a bug when the OpenWrt WAN network goes down for a minute, then is again reconnected to the same WAN defined zone.  
so it's called the isp-interface right so,

once it down:
- we loose the default route 0.0.0.0/0 on device isp-gateway  
- yggdrasil continues to work on LAN and Mesh interfaces
- peers over isp-interface and coords update

once up:
- the isp-interface still has null route entries for IP peers via isp-interface  
- yggdrasil cannot reach these autoygg-servers directly

null routes prevent 1 form of causing a double peering with multiple meshnode-autoygg-servers in the mesh

**Comment by cure** [comment] 2020-08-12 01:04
I can reproduce the problem. Those blackhole routes sure are causing a lot of complications. I guess there are a few options

a) stop adding those null routes. I think Yggdrasil should protect against routing its peer traffic over itself; trying to build in extra belts and suspenders at the layer above it feels wrong (and clearly leads to complications). This bug would not exist...

b) make the null routes interface specific. It's only the yggdrasil tunnel interface that we never want to send this traffic to, right? I don't think we can create a blackhole route with a device attached; but maybe we can mimic a blackhole route somehow with a special route attached to the tunnel interface? Or maybe we can insert a firewall rule that has that effect?

c) make the null routes disappear automatically when the default gateway disappears and the autoygg server becomes unreachable. I suppose some sort of watchdog process inside the autoygg client could periodically check connectivity to the autoygg server and if it can't reach it anymore, remove the client routes (or even tear down everything). And try to re-connect after that.

What should we do?

**Comment by wfleurant** [comment] 2020-08-20 13:31
I have 2 ideas I want to add.  

d) Use the hotplug event system.  
Here's an example from the shorewall VPN [hotplug script](https://github.com/openwrt/packages/blob/master/net/shorewall/files/hotplug_iface)  
Then perhaps from this script we can re-run the `autoygg --action renew` command?  
If we used this method we could later introduce a protections if/when the WAN cable is constantly going down and up (flapping).  

e) Configure yggdrasil with  `InterfacePeers: {}` instead of `Peers: []`

**Comment by cure** [comment] 2020-08-21 02:44
d) is a good workaround for this bug. I've pushed a commit to the mm-toolbox repo that adds a hotplug file. It restarts autoygg-client on any 'ifup' event.

for e), it seems like what we should be doing is

  InterfacePeers: {
    "wan": [
      tcp://a.b.c.d:xxxxx
      tls://a.b.c.d:xxxxx
    ]
  }

but in the /etc/config/yggdrasil file. So... instead of populating our hardcoded peers in the Peers section, we should be doing that in the Interface Peers section, on the wan interface. Will that break anything? 

If not, let's do that. Can we then drop this whole business with the null routes in autoygg-client?

**Comment by cure** [comment] 2020-08-21 02:58
I tried using InterfacePeers by moving all my peers to the 'wan' interface. It seems to simply not work. No active peers, no errors.

**Comment by wfleurant** [comment] 2020-08-27 16:47
We can now pivot away from peers and introduce interfacePeers on 'eth1' so to never use 'ygg0' and then phase out null routes. i can see replacing null routes with a forward filter to prevent any other router in the mesh from double peering through CKR.

**Comment by cure** [comment] 2020-09-05 12:06
Switch to InterfacePeers in [PR 92 on the meta-imagebuilder repo](https://github.com/MassMesh/meta-imagebuilder/pull/92), ready for review.

Can you elaborate a bit on the forward filters you have in mind?

**Comment by cure** [comment] 2020-12-19 21:28
Since we've now switched to InterfacePeers, dropped the null routes altogether, and have the hotplug file present, I'm going to close this issue.

**Closed as completed by cure** 2020-12-19 21:28 UTC
